apiVersion: v1
kind: Service
metadata:
  name: eirini-helloworld-extension-service
spec:
  selector:
    app: eirini-helloworld-extension
  ports:
  - protocol: TCP
    port: 4545
    targetPort: 4545
  clusterIP: 10.114.0.239
